[
  {
    "login": "marvin",
    "id": 557,
    "node_id": "MDQ6VXNlcjU1Nw==",
    "avatar_url": "https://avatars.githubusercontent.com/u/557?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/marvin",
    "html_url": "https://github.com/marvin",
    "followers_url": "https://api.github.com/users/marvin/followers",
    "following_url": "https://api.github.com/users/marvin/following{/other_user}",
    "gists_url": "https://api.github.com/users/marvin/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/marvin/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/marvin/subscriptions",
    "organizations_url": "https://api.github.com/users/marvin/orgs",
    "repos_url": "https://api.github.com/users/marvin/repos",
    "events_url": "https://api.github.com/users/marvin/events{/privacy}",
    "received_events_url": "https://api.github.com/users/marvin/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "komapa",
    "id": 577,
    "node_id": "MDQ6VXNlcjU3Nw==",
    "avatar_url": "https://avatars.githubusercontent.com/u/577?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/komapa",
    "html_url": "https://github.com/komapa",
    "followers_url": "https://api.github.com/users/komapa/followers",
    "following_url": "https://api.github.com/users/komapa/following{/other_user}",
    "gists_url": "https://api.github.com/users/komapa/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/komapa/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/komapa/subscriptions",
    "organizations_url": "https://api.github.com/users/komapa/orgs",
    "repos_url": "https://api.github.com/users/komapa/repos",
    "events_url": "https://api.github.com/users/komapa/events{/privacy}",
    "received_events_url": "https://api.github.com/users/komapa/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "andrew",
    "id": 1060,
    "node_id": "MDQ6VXNlcjEwNjA=",
    "avatar_url": "https://avatars.githubusercontent.com/u/1060?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/andrew",
    "html_url": "https://github.com/andrew",
    "followers_url": "https://api.github.com/users/andrew/followers",
    "following_url": "https://api.github.com/users/andrew/following{/other_user}",
    "gists_url": "https://api.github.com/users/andrew/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/andrew/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/andrew/subscriptions",
    "organizations_url": "https://api.github.com/users/andrew/orgs",
    "repos_url": "https://api.github.com/users/andrew/repos",
    "events_url": "https://api.github.com/users/andrew/events{/privacy}",
    "received_events_url": "https://api.github.com/users/andrew/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "gruner",
    "id": 2345,
    "node_id": "MDQ6VXNlcjIzNDU=",
    "avatar_url": "https://avatars.githubusercontent.com/u/2345?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/gruner",
    "html_url": "https://github.com/gruner",
    "followers_url": "https://api.github.com/users/gruner/followers",
    "following_url": "https://api.github.com/users/gruner/following{/other_user}",
    "gists_url": "https://api.github.com/users/gruner/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/gruner/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/gruner/subscriptions",
    "organizations_url": "https://api.github.com/users/gruner/orgs",
    "repos_url": "https://api.github.com/users/gruner/repos",
    "events_url": "https://api.github.com/users/gruner/events{/privacy}",
    "received_events_url": "https://api.github.com/users/gruner/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "pfefferle",
    "id": 2373,
    "node_id": "MDQ6VXNlcjIzNzM=",
    "avatar_url": "https://avatars.githubusercontent.com/u/2373?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/pfefferle",
    "html_url": "https://github.com/pfefferle",
    "followers_url": "https://api.github.com/users/pfefferle/followers",
    "following_url": "https://api.github.com/users/pfefferle/following{/other_user}",
    "gists_url": "https://api.github.com/users/pfefferle/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/pfefferle/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/pfefferle/subscriptions",
    "organizations_url": "https://api.github.com/users/pfefferle/orgs",
    "repos_url": "https://api.github.com/users/pfefferle/repos",
    "events_url": "https://api.github.com/users/pfefferle/events{/privacy}",
    "received_events_url": "https://api.github.com/users/pfefferle/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "Aeon",
    "id": 2532,
    "node_id": "MDQ6VXNlcjI1MzI=",
    "avatar_url": "https://avatars.githubusercontent.com/u/2532?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Aeon",
    "html_url": "https://github.com/Aeon",
    "followers_url": "https://api.github.com/users/Aeon/followers",
    "following_url": "https://api.github.com/users/Aeon/following{/other_user}",
    "gists_url": "https://api.github.com/users/Aeon/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Aeon/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Aeon/subscriptions",
    "organizations_url": "https://api.github.com/users/Aeon/orgs",
    "repos_url": "https://api.github.com/users/Aeon/repos",
    "events_url": "https://api.github.com/users/Aeon/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Aeon/received_events",
    "type": "User",
    "site_admin": false
  }
]